title: "Liu Woods's Website"
description: [Hello and welcome to my website! I like developing Windows programs and studying the weather. My YouTube is https://youtube.com/LiuWoods.]
email: HomicidalLiu666@outlook.com
baseurl: "/" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nan
github_username:  HatsuneMikuCode
remote_theme: "godalming123/minimal"
plugins:
- jekyll-remote-theme
analytics:
  provider               : "google-gtag"
  google:
    measurement_id          : "G-24JXX04WQL"
    anonymize_ip         : false


# theme: jekyll-theme-cayman
