title: "Liu Woods's Website"
description: [Liu Woods's website/blog]
email: mysite@example.com
baseurl: "/" # the subpath of your site, e.g. /blog
url: "liuwoodscode.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nan
github_username:  HatsuneMikuCode
remote_theme: "godalming123/minimal"
plugins:
- jekyll-remote-theme
google_analytics: UA-198119152-3


# theme: jekyll-theme-cayman
